spring:
  datasource:
    url: jdbc:h2:file:./data/flashdb;DB_CLOSE_DELAY=-1;MODE=MySQL;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate.format_sql: false
  h2:
    console:
      enabled: true

# 톰캣/커넥션풀 기본치 살짝 상향(실험 편의)
server:
  tomcat:
    threads:
      max: 400

# Hikari (기본 10 → 30)
spring.datasource.hikari:
  maximum-pool-size: 30

# 결제 모의 지연(외부 PG 호출 대체). 필요시 조절
mock:
  payment:
    delay-ms: 200

spring.kafka:
  bootstrap-servers: localhost:9092
  consumer:
    group-id: flashsale-order-group